"""Upgrade countries table

Revision ID: 09623cef9298
Revises: bcb7f4761864
Create Date: 2025-05-28 13:32:58.767063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09623cef9298'
down_revision: Union[str, None] = 'bcb7f4761864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=True),
    sa.Column('numeric_code', sa.String(length=3), nullable=True),
    sa.Column('iso2', sa.String(length=2), nullable=True),
    sa.Column('phonecode', sa.String(length=255), nullable=True),
    sa.Column('capital', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('currency_name', sa.String(length=255), nullable=True),
    sa.Column('currency_symbol', sa.String(length=255), nullable=True),
    sa.Column('tld', sa.String(length=255), nullable=True),
    sa.Column('native', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('subregion', sa.String(length=255), nullable=True),
    sa.Column('subregion_id', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('timezones', sa.Text(), nullable=True),
    sa.Column('translations', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('emoji', sa.String(length=191), nullable=True),
    sa.Column('emojiU', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('flag', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('wikiDataId', sa.String(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_region_id'), 'countries', ['region_id'], unique=False)
    op.create_index(op.f('ix_countries_subregion_id'), 'countries', ['subregion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_subregion_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_region_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
