"""Update post table

Revision ID: 0e5e06b4a2df
Revises: 9c481672b76b
Create Date: 2024-12-04 09:14:16.433136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5e06b4a2df'
down_revision: Union[str, None] = '9c481672b76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('pets_owner_id_fkey', 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'])
    op.drop_column('pets', 'profile_picture')
    op.drop_column('pets', 'owner_id')
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('media_url', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('visibility', sa.String(), server_default='public', nullable=False))
    op.add_column('posts', sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False, comment='Indicates if the post is active'))
    op.add_column('posts', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('location', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('parent_post_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.drop_constraint('posts_owner_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'pets', ['pet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'posts', 'posts', ['parent_post_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'published')
    op.drop_column('posts', 'owner_id')
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_picture_url')
    op.add_column('posts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_owner_id_fkey', 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('posts', 'edited_at')
    op.drop_column('posts', 'parent_post_id')
    op.drop_column('posts', 'comments_count')
    op.drop_column('posts', 'likes_count')
    op.drop_column('posts', 'location')
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'is_active')
    op.drop_column('posts', 'visibility')
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_url')
    op.drop_column('posts', 'pet_id')
    op.drop_column('posts', 'user_id')
    op.add_column('pets', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pets', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key('pets_owner_id_fkey', 'pets', 'users', ['owner_id'], ['id'])
    op.drop_column('pets', 'user_id')
    op.drop_column('pets', 'profile_picture_url')
    # ### end Alembic commands ###
