"""Upgrade countries table

Revision ID: 1847a9bb2a8e
Revises: 9e8a6fea80a8
Create Date: 2025-05-28 13:24:42.435709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1847a9bb2a8e'
down_revision: Union[str, None] = '9e8a6fea80a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('iso3', sa.String(length=3), nullable=True))
    op.add_column('countries', sa.Column('iso2', sa.String(length=2), nullable=True))
    op.add_column('countries', sa.Column('phonecode', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('capital', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('currency', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('currency_name', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('currency_symbol', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('tld', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('native', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('region', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('subregion', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('nationality', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('timezones', sa.Text(), nullable=True))
    op.add_column('countries', sa.Column('translations', sa.Text(), nullable=True))
    op.add_column('countries', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('countries', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('countries', sa.Column('emoji', sa.String(length=191), nullable=True))
    op.add_column('countries', sa.Column('emojiU', sa.String(length=191), nullable=True))
    op.add_column('countries', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('countries', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('countries', sa.Column('flag', sa.SmallInteger(), server_default=sa.text('1'), nullable=False))
    op.add_column('countries', sa.Column('wikiDataId', sa.String(length=255), nullable=True, comment='Rapid API GeoDB Cities'))
    op.drop_constraint('countries_alpha2_code_key', 'countries', type_='unique')
    op.drop_constraint('countries_alpha3_code_key', 'countries', type_='unique')
    op.create_index(op.f('ix_countries_region_id'), 'countries', ['region_id'], unique=False)
    op.create_index(op.f('ix_countries_subregion_id'), 'countries', ['subregion_id'], unique=False)
    op.drop_column('countries', 'flag_url')
    op.drop_column('countries', 'alpha3_code')
    op.drop_column('countries', 'alpha2_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('alpha2_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('countries', sa.Column('alpha3_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('countries', sa.Column('flag_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_countries_subregion_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_region_id'), table_name='countries')
    op.create_unique_constraint('countries_alpha3_code_key', 'countries', ['alpha3_code'])
    op.create_unique_constraint('countries_alpha2_code_key', 'countries', ['alpha2_code'])
    op.drop_column('countries', 'wikiDataId')
    op.drop_column('countries', 'flag')
    op.drop_column('countries', 'updated_at')
    op.drop_column('countries', 'created_at')
    op.drop_column('countries', 'emojiU')
    op.drop_column('countries', 'emoji')
    op.drop_column('countries', 'longitude')
    op.drop_column('countries', 'latitude')
    op.drop_column('countries', 'translations')
    op.drop_column('countries', 'timezones')
    op.drop_column('countries', 'nationality')
    op.drop_column('countries', 'subregion')
    op.drop_column('countries', 'region')
    op.drop_column('countries', 'native')
    op.drop_column('countries', 'tld')
    op.drop_column('countries', 'currency_symbol')
    op.drop_column('countries', 'currency_name')
    op.drop_column('countries', 'currency')
    op.drop_column('countries', 'capital')
    op.drop_column('countries', 'phonecode')
    op.drop_column('countries', 'iso2')
    op.drop_column('countries', 'iso3')
    # ### end Alembic commands ###
