"""Add is_for_sale to Pet model

Revision ID: 4bc77c7917a8
Revises: d26bc820e0cf
Create Date: 2025-06-28 19:51:24.351932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc77c7917a8'
down_revision: Union[str, None] = 'd26bc820e0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_for_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'is_for_sale')
    # ### end Alembic commands ###
