"""add pet table

Revision ID: 54410bf7eeca
Revises: e777f0b08463
Create Date: 2024-11-30 18:01:16.668382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54410bf7eeca'
down_revision: Union[str, None] = 'e777f0b08463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('animal_type', sa.String(), nullable=False),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.Column('breed_1', sa.String(), nullable=True),
    sa.Column('breed_2', sa.String(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.drop_table('pets')
    # ### end Alembic commands ###
