"""Change image to image_url in drop-down list

Revision ID: 622c2f773dd5
Revises: b1dff7b466df
Create Date: 2024-12-12 18:37:41.787725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622c2f773dd5'
down_revision: Union[str, None] = 'b1dff7b466df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_types', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('animal_types', 'image')
    op.add_column('pet_types', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('pet_types', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_types', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pet_types', 'image_url')
    op.add_column('animal_types', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('animal_types', 'image_url')
    # ### end Alembic commands ###
