"""Refactor UserRelationship model

Revision ID: 70c7b3af3695
Revises: cb687803cb49
Create Date: 2025-01-18 00:29:33.739447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c7b3af3695'
down_revision: Union[str, None] = 'cb687803cb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_relationships_receiver_id'), 'user_relationships', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_user_relationships_requester_id'), 'user_relationships', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_relationships_requester_id'), table_name='user_relationships')
    op.drop_index(op.f('ix_user_relationships_receiver_id'), table_name='user_relationships')
    # ### end Alembic commands ###
