"""Add nickname to Pet model

Revision ID: 7ef39ac82521
Revises: 4bc77c7917a8
Create Date: 2025-06-28 19:57:51.977570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef39ac82521'
down_revision: Union[str, None] = '4bc77c7917a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
