"""Create countries table

Revision ID: 9e8a6fea80a8
Revises: 70c7b3af3695
Create Date: 2025-05-28 13:11:04.539047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8a6fea80a8'
down_revision: Union[str, None] = '70c7b3af3695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alpha2_code', sa.String(length=2), nullable=False),
    sa.Column('alpha3_code', sa.String(length=3), nullable=False),
    sa.Column('numeric_code', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('subregion_id', sa.Integer(), nullable=True),
    sa.Column('flag_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha2_code'),
    sa.UniqueConstraint('alpha3_code')
    )
    op.drop_constraint('pets_user_id_fkey', 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key('pets_user_id_fkey', 'pets', 'users', ['user_id'], ['id'])
    op.drop_table('countries')
    # ### end Alembic commands ###
