"""Add the field 'image_url' to the table 'breeds'.

Revision ID: afde03a36522
Revises: a6fd78ce6550
Create Date: 2024-12-19 00:44:22.705695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afde03a36522'
down_revision: Union[str, None] = 'a6fd78ce6550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breeds', 'image_url')
    # ### end Alembic commands ###
