"""Upgrade countries table

Revision ID: bcb7f4761864
Revises: b7e7d99252d6
Create Date: 2025-05-28 13:32:15.682263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcb7f4761864'
down_revision: Union[str, None] = 'b7e7d99252d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_countries_region_id', table_name='countries')
    op.drop_index('ix_countries_subregion_id', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numeric_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subregion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iso3', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('iso2', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('phonecode', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('capital', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('currency_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('currency_symbol', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tld', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('native', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subregion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timezones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('translations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True),
    sa.Column('emoji', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('emojiU', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('flag', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Rapid API GeoDB Cities'),
    sa.PrimaryKeyConstraint('id', name='countries_pkey')
    )
    op.create_index('ix_countries_subregion_id', 'countries', ['subregion_id'], unique=False)
    op.create_index('ix_countries_region_id', 'countries', ['region_id'], unique=False)
    # ### end Alembic commands ###
