"""Add private_account to users table

Revision ID: cb687803cb49
Revises: bb25493f65d5
Create Date: 2025-01-12 21:23:58.451333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb687803cb49'
down_revision: Union[str, None] = 'bb25493f65d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('private_account', sa.Boolean(), nullable=True))
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'private_account')
    # ### end Alembic commands ###
