"""Fix country name

Revision ID: d26bc820e0cf
Revises: 150ee344a78f
Create Date: 2025-06-28 11:19:56.737159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26bc820e0cf'
down_revision: Union[str, None] = '150ee344a78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_constraint('pets_counrty_id_fkey', 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'countries', ['country_id'], ['id'], ondelete='SET NULL')
    op.drop_column('pets', 'counrty_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('counrty_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key('pets_counrty_id_fkey', 'pets', 'countries', ['counrty_id'], ['id'], ondelete='SET NULL')
    op.drop_column('pets', 'country_id')
    # ### end Alembic commands ###
