"""Set nullable=True for pet.gender

Revision ID: e56fe5f2ecf6
Revises: 6ed05137ce2a
Create Date: 2024-12-09 23:16:04.521993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56fe5f2ecf6'
down_revision: Union[str, None] = '6ed05137ce2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
