"""Update post table

Revision ID: ee515de854d3
Revises: 0e5e06b4a2df
Create Date: 2024-12-04 09:23:04.774443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee515de854d3'
down_revision: Union[str, None] = '0e5e06b4a2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), server_default='public', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False, comment='Indicates if the post is active'),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'votes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_table('posts')
    # ### end Alembic commands ###
